# Generated by Django 2.2.5 on 2019-10-04 03:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SpeechTherapy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textsample',
            name='file',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='SpeechTherapy.File'),
        ),
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_recorded', models.DateTimeField(auto_now_add=True, verbose_name='Date recorded.')),
                ('score', models.DecimalField(decimal_places=2, max_digits=3, null=True)),
                ('audio', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='audio', to='SpeechTherapy.File')),
                ('interpretation', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='interpretation', to='SpeechTherapy.File')),
                ('text_sample', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='SpeechTherapy.TextSample')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
