# Generated by Django 2.2.5 on 2019-10-22 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpeechTherapy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='textsample',
            name='name',
            field=models.TextField(default='asdf'),
            preserve_default=False,
        ),
    ]
