# Generated by Django 2.2.5 on 2019-10-15 02:49

import SpeechTherapy.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpeechTherapy', '0002_auto_20191003_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='recording',
            name='name',
            field=models.CharField(default=SpeechTherapy.models.defaultDateTime, max_length=32),
        ),
    ]
