# Generated by Django 2.2.5 on 2019-10-22 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpeechTherapy', '0002_textsample_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='textsample',
            name='expected_time',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
