# Generated by Django 2.2.5 on 2019-10-27 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpeechTherapy', '0003_textsample_expected_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textsample',
            name='name',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='textsample',
            name='text',
            field=models.TextField(unique=True),
        ),
    ]
