# Generated by Django 2.2.5 on 2019-10-15 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpeechTherapy', '0003_recording_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recording',
            name='audio',
            field=models.FileField(upload_to='audio'),
        ),
        migrations.AlterField(
            model_name='recording',
            name='interpretation',
            field=models.FileField(upload_to='interpretation/'),
        ),
        migrations.AlterField(
            model_name='recording',
            name='score',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='textsample',
            name='file',
            field=models.FileField(upload_to='textSamples/'),
        ),
        migrations.DeleteModel(
            name='File',
        ),
    ]
