# Generated by Django 2.2.5 on 2019-10-16 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpeechTherapy', '0004_auto_20191014_2110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textsample',
            name='file',
        ),
        migrations.AddField(
            model_name='textsample',
            name='text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recording',
            name='audio',
            field=models.FileField(upload_to='audio/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='recording',
            name='interpretation',
            field=models.TextField(),
        ),
    ]
