# Generated by Django 2.2.5 on 2019-10-16 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpeechTherapy', '0005_auto_20191015_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recording',
            name='date_recorded',
            field=models.DateTimeField(),
        ),
    ]
